workflows:
    react-native:
        name: React Native App
        environment:
            node: latest
        scripts:
            - yarn install
            - yarn
            - |
              # clean gradlew
              cd android
              ./gradlew clean
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # make sudo 
                cd android
                chmod +x gradlew
            - |
                # build Android
                cd android
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/**/*.apk
        publishing:
          email:
            recipients:
              - th.thoong@gmail.com
