workflows:
    react-native:
        name: React Native App
        environment:
            node: latest
        scripts:
            - yarn install
            - yarn
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                cd android
                chmod +x gradlew
            - |
                # build Android
                cd android
                ./gradlew assembleDebug
        artifacts:
            - android/app/build/outputs/**/**/*.apk
