workflows:

    react-native:
        triggering:
          events:
            - push
          branch_patterns: 
            - pattern: develop
              include: false
          cancel_previous_builds: true
        name: React Native App
        environment:
            node: latest
        scripts:
            - yarn install
            - yarn
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - |
                # make sudo 
                cd android
                chmod +x gradlew
            - |
              # clean gradlew
              cd android
              ./gradlew clean
            - |
                # build Android
                cd android
                ./gradlew assembleRelease --warning-mode all
            - |
                # build iOS
                cd ios
                pod install
                xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - android/app/build/outputs/**/**/*.apk
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        publishing:
          email:
            recipients:
              - th.thoong@gmail.com
