workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.petshopapp"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          yarn install
          yarn
      - name: Install Expo CLI and eject
        script: | 
          yarn react-native run-android
      - name: Set up app/build.gradle
        script: | 
          mv ./support-files/build.gradle android/app 
    artifacts:
      - android/app/build/outputs/**/*.aab
